### ISSUE TITLE
Link to editor spreadsheet broken

### ISSUE THREAD

**Issue by Bobobalink** [enenra/ersa#19]
The link to the spreadsheet on the wiki is broken, as it points to editing the spreadsheet and thus requires edit permissions to navigate to it.

**Comment by enenra** [comment]
Ah, my bad. I didn't replace all the links with the new one. That should be done now. 

https://docs.google.com/spreadsheets/d/1-tUQyizY8Rhp9GslGgpWbjQ6SKNS5A4xd_wTp4a_jmE/edit

Where did you click the link? On the How to use the Spreadsheet wiki page?

**Comment by Bobobalink** [comment]
Yes, but works now. All is well.

**Comment by enenra** [comment]
Great! Thanks for bringing it to my attention!
